### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by gorrem** [VazkiiMods/Patchouli#400]
![imagen_2021-05-14_155946](https://user-images.githubusercontent.com/84202678/118316600-68887200-b4cd-11eb-86a6-23c814749160.png)
My minecraft dont load Patchouli and i dont know why. I Tried everything, reinstaling launcher, reinstalling the mod and nothing changed this is the ONLY mod i have trouble with
---- Minecraft Crash Report ----
// There are four lights!

Time: 14/05/21 15:41
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:429) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,xf:fml:fairylights:GameRendererTransformer}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[ForgeOptiFine%201.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[gson-2.8.0.jar:?] {}
-- MOD patchouli --
Details:
	Caused by 0: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
		at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[gson-2.8.0.jar:?] {}
		at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?] {}
		at com.google.gson.Gson.fromJson(Gson.java:825) ~[gson-2.8.0.jar:?] {}
		at vazkii.patchouli.common.util.SerializationUtil.loadFromFile(SerializationUtil.java:38) ~[patchouli:1.16.4-51] {re:classloading}
		at vazkii.patchouli.common.util.SerializationUtil.loadFromFile(SerializationUtil.java:26) ~[patchouli:1.16.4-51] {re:classloading}
		at vazkii.patchouli.client.base.PersistentData.load(PersistentData.java:27) ~[patchouli:1.16.4-51] {re:classloading}
		at vazkii.patchouli.client.base.PersistentData.setup(PersistentData.java:23) ~[patchouli:1.16.4-51] {re:classloading}
		at vazkii.patchouli.client.base.ClientProxy.setupClient(ClientProxy.java:30) ~[patchouli:1.16.4-51] {re:classloading}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_291] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_291] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_291] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_291] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_291] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_291] {}

	Mod File: Patchouli-1.16.4-51.jar
	Failure message: Patchouli (patchouli) encountered an error during the sided_setup event phase
		com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	Mod Version: 1.16.4-51
	Mod Issue URL: https://github.com/Vazkii/Patchouli
	Exception message: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
Stacktrace:
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:825) ~[gson-2.8.0.jar:?] {}
	at vazkii.patchouli.common.util.SerializationUtil.loadFromFile(SerializationUtil.java:38) ~[patchouli:1.16.4-51] {re:classloading}
	at vazkii.patchouli.common.util.SerializationUtil.loadFromFile(SerializationUtil.java:26) ~[patchouli:1.16.4-51] {re:classloading}
	at vazkii.patchouli.client.base.PersistentData.load(PersistentData.java:27) ~[patchouli:1.16.4-51] {re:classloading}
	at vazkii.patchouli.client.base.PersistentData.setup(PersistentData.java:23) ~[patchouli:1.16.4-51] {re:classloading}
	at vazkii.patchouli.client.base.ClientProxy.setupClient(ClientProxy.java:30) ~[patchouli:1.16.4-51] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_291] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_291] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4467388888 bytes (4260 MB) / 5872025600 bytes (5600 MB) up to 5872025600 bytes (5600 MB)
	CPUs: 4
	JVM Flags: 10 total; -Xmn128M -Xmx5580M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.16.4_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.37.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.37
	FML Language Providers: 
		javafml@35.1
		minecraft@1
		kotori_scala@2.13.5-build-2
	Mod List: 
		forge-1.16.4-35.1.37-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |ENQUEUE_IM|NOSIGNATURE
		industrial-foregoing-1.16.4-3.2.8.1-f2c848c.jar   |Industrial Foregoing          |industrialforegoing           |3.2.8.1             |ENQUEUE_IM|NOSIGNATURE
		mowziesmobs-1.5.16.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.16              |ENQUEUE_IM|NOSIGNATURE
		titanium-1.16.4-3.2.5.jar                         |Titanium                      |titanium                      |3.2.5               |ENQUEUE_IM|NOSIGNATURE
		AdditionalEnchantedMiner-1.16.5-16.1.6.jar        |QuarryPlus                    |quarryplus                    |16.1.6              |ENQUEUE_IM|1a:13:52:63:6f:dc:0c:ad:7f:8a:64:ac:46:58:8a:0c:90:ea:2c:5d:11:ac:4c:d4:62:85:c7:d1:00:fa:9c:76
		torchslabmod-1.16.4_v1.6.18.jar                   |Torch Slab Mod                |torchslabmod                  |1.6.18              |ENQUEUE_IM|NOSIGNATURE
		ImmersiveEngineering-1.16.4-4.1.2-129.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.2-129    |ENQUEUE_IM|44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		BiomesOPlenty-1.16.4-13.0.0.440-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.439   |ENQUEUE_IM|NOSIGNATURE
		EndRemastered-R352.jar                            |End Remastered 3.5.2          |endrem                        |1.16.3              |ENQUEUE_IM|NOSIGNATURE
		jei-1.16.5-7.6.4.90.jar                           |Just Enough Items             |jei                           |7.6.4.90            |ENQUEUE_IM|NOSIGNATURE
		fairylights-4.0.4-1.16.4.jar                      |Fairy Lights                  |fairylights                   |4.0.4               |ENQUEUE_IM|NOSIGNATURE
		curios-forge-1.16.4-4.0.3.5.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.5      |ENQUEUE_IM|NOSIGNATURE
		Patchouli-1.16.4-51.jar                           |Patchouli                     |patchouli                     |1.16.4-51           |ERROR     |NOSIGNATURE
		Xaeros_Minimap_21.7.0_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.7.0              |ENQUEUE_IM|NOSIGNATURE
		enchantedwolves-1.1.0.1.jar                       |Enchanted Wolves              |enchantedwolves               |1.1.0.1             |ENQUEUE_IM|NOSIGNATURE
		ExtraSpace+1.0.6+1.16.5.jar                       |extraspace                    |extraspace                    |1.0.6               |ENQUEUE_IM|NOSIGNATURE
		Decoration+and+Furniture+Mod+1.16.4.jar           |Decoration and furniture mod  |decoration_mod                |1.1.0               |ENQUEUE_IM|NOSIGNATURE
		TravelersBackpack-1.16.4-5.3.8.jar                |Traveler's Backpack           |travelersbackpack             |5.3.8               |ENQUEUE_IM|NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |ENQUEUE_IM|d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		mcw-doors-1.0.2-mc1.16.5.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.2               |ENQUEUE_IM|NOSIGNATURE
		furniture-7.0.0-pre19-1.16.3.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |ENQUEUE_IM|NOSIGNATURE
		observerlib-1.16.4-1.5.1.jar                      |ObserverLib                   |observerlib                   |1.16.4-1.5.1        |ENQUEUE_IM|NOSIGNATURE
		mcw-furniture-2.0.1-mc1.16.5.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.1               |ENQUEUE_IM|NOSIGNATURE
		OddWaterMobs[1.16.4]_1.2.3.jar                    |Odd Water Mobs                |oddwatermobs                  |1.2.3               |ENQUEUE_IM|NOSIGNATURE
		mysticalworld-1.16.4-0.3.1.10.jar                 |Mystical World                |mysticalworld                 |1.16.4-0.3.1.10     |ENQUEUE_IM|NOSIGNATURE
		forge-1.16.4-35.1.37-universal.jar                |Forge                         |forge                         |35.1.37             |ENQUEUE_IM|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BloodMagic-1.16.4-3.1.0-15.jar                    |Blood Magic                   |bloodmagic                    |1.16.4-3.1.0-15     |ENQUEUE_IM|NOSIGNATURE
		VillagersAndMonstersMod4.3.jar                    |VillagerAndMonsterMod         |villigeandmonstermod          |1.0.0               |ENQUEUE_IM|NOSIGNATURE
		tl_skin_cape_forge_1.16.4-1.16.jar                |TLSkinCape                    |tlskincape                    |1.6                 |ENQUEUE_IM|19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		SubWild-1.16.4-1.1.1.jar                          |Subterranean Wilderness       |subwild                       |1.1.1               |ENQUEUE_IM|NOSIGNATURE
		dungeonsarise1.16.4-1.2.63a.jar                   |Dungeons Arise                |dungeons_arise                |1.2.63a             |ENQUEUE_IM|NOSIGNATURE
		UselessSword-1.16.4-V1.2.8.jar                    |Useless Sword                 |useless_sword                 |1.2.8               |ENQUEUE_IM|NOSIGNATURE
	Crash Report UUID: bd95b90e-82f3-4cf6-a7ed-520bc091e154
	OptiFine Version: OptiFine_1.16.4_HD_U_G7
	OptiFine Build: 20210221-012854
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.5.13417 Compatibility Profile Context 15.301.1901.0
	OpenGlRenderer: AMD Radeon HD 7500/7600 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Hubry** [comment]
Post the crash report, a screenshot is absolutely useless.

**Comment by williewillus** [comment]
Your .minecraft/patchouli_data.json got corrupted, delete it.
In modern versions the mod is more robust to this.
