### ISSUE TITLE
I dont know if its patchouli crashing me or not but in the crash report it did say something about it

### ISSUE THREAD

**Issue by chadica** [VazkiiMods/Patchouli#423]
I was playing medivial minecraft pack and the pack keeps crashing on me
Here is part of the crash report 
-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at net.minecraft.class_359.method_1957(class_359.java:64)
	at net.minecraft.class_329.method_1753(class_329.java:368)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$dfm000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:36)
	at net.minecraft.class_310.method_1514(class_310.java:754)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by williewillus** [comment]
this has nothing to do with patchouli. Note that it says the open book context is n/a, aka no patchouli book was open at the time.

Either post a full debug.log or this isn't a patchouli issue.
