### ISSUE TITLE
Fabric Patchouli + Fabric rendering destroying framerates & world rendering on server

### ISSUE THREAD

**Issue by ghost** [VazkiiMods/Patchouli#437]
I can't quite figure out the issue, but certain chunks seem to get corrupted and when they render framerate drops to 1 and a bunch of chunks turn invisible. RAM usage on client + server is normal. Tried digging into the log myself but Im unfamiliar with fabric and MC code
![2021-08-26_17 27 54]
Image is a friend experience the same issue playing on a small server. 
(https://user-images.githubusercontent.com/25110667/131048488-23c85928-d7a3-4229-ba47-cdbccc2e0505.png)

Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at vazkii.patchouli.client.handler.BookRightClickHandler.getHoveredEntry(BookRightClickHandler.java:97)
	at vazkii.patchouli.client.handler.BookRightClickHandler.onRenderHUD(BookRightClickHandler.java:39)
	at vazkii.patchouli.client.handler.BookRightClickHandler$$Lambda$9760/1837824953.onHudRender(Unknown Source)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback$$Lambda$9356/1487526896.onHudRender(Unknown Source)
	at net.minecraft.client.gui.hud.InGameHud.handler$zdm000$render(InGameHud:1841)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:376)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:597)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.MinecraftClient.handler$bfl000$afterCrashHandled(MinecraftClient:8404)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:704)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
-----------------------------------------------------------------------------------
Stacktrace:
-----------------------------------------------------------------------------------
        at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$bfl000$onCrash(class_310.java:8412)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.class_310.handler$bfl000$afterCrashHandled(class_310.java:8404)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
------------------------------------------------------------------------------------
Additionally, session logs show thousands of these:
[19:21:30] [main/INFO]: WorldRenderer reloaded minecraft:overworld
[19:21:30] [main/INFO]: WorldRenderer reloaded minecraft:the_end
[19:21:30] [main/INFO]: WorldRenderer reloaded minecraft:the_nether
[19:21:30] [main/INFO]: WorldRenderer reloaded minecraft:the_end
[19:21:30] [main/INFO]: WorldRenderer reloaded minecraft:the_nether
[19:21:30] [main/INFO]: WorldRenderer reloaded minecraft:overworld
[19:21:30] [main/INFO]: WorldRenderer reloaded minecraft:overworld
[19:21:30] [main/INFO]: WorldRenderer reloaded minecraft:the_end
Although I doubt Patchouli has anything to do with this, I am sure it's related to the issue.

**Comment by williewillus** [comment]
should be improved in modern versions
