### ISSUE TITLE
Update to 1.17.1

### ISSUE THREAD

**Issue by xz123456xz** [VazkiiMods/Patchouli#459]
Please update the Forge version of Patchouli to 1.17.1 Thank you~~

**Comment by williewillus** [comment]
Does the current version not work in 1.17.1? usually things are forward compatible within the major version

**Comment by xz123456xz** [comment]
[1211月2021 11:40:41.975] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, xz123456xz, --version, 1.17.1-forge-37.0.107, --gameDir, C:\Users\User\AppData\Roaming\.minecraft, --assetsDir, C:\Users\User\AppData\Roaming\.minecraft\assets, --assetIndex, 1.17, --uuid, db5b0cc5fd4c4f9daa4880bd909d5df8, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 37.0.107, --fml.mcVersion, 1.17.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210706.113038]
[1211月2021 11:40:41.981] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 16.0.1 by Microsoft
[1211月2021 11:40:42.118] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=union:/C:/Users/User/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar%2318! Service=ModLauncher Env=CLIENT
[1211月2021 11:40:43.901] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[1211月2021 11:40:43.903] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.17.1-forge-37.0.107, --gameDir, C:\Users\User\AppData\Roaming\.minecraft, --assetsDir, C:\Users\User\AppData\Roaming\.minecraft\assets, --uuid, db5b0cc5fd4c4f9daa4880bd909d5df8, --username, xz123456xz, --assetIndex, 1.17, --accessToken, ????????, --userType, msa, --versionType, release]
[1211月2021 11:40:43.912] [main/WARN] [mixin/]: Reference map 'croptopia.refmap.json' for croptopia.mixins.json could not be read. If this is a development environment you can ignore this message
[1211月2021 11:40:44.264] [main/INFO] [net.minecraftforge.coremod.CoreMod.creativecore/COREMODLOG]: Done
[1211月2021 11:40:44.398] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/multiplayer/ClientAdvancementManager (java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.ClientAdvancementManager)
[1211月2021 11:40:44.398] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.multiplayer.ClientAdvancementManager was not found assets/patchouli/patchouli.mixins.json:client.MixinClientAdvancementManager
[1211月2021 11:40:49.394] [Render thread/WARN] [mixin/]: @Final field f_96540_:Ljava/util/List; in iceberg.mixins.json:ScreenMixin should be final
[11:40:49] [Render thread/WARN]: Assets URL 'union:/C:/Users/User/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.17.1-20210706.113038/client-1.17.1-20210706.113038-srg.jar%2383!/assets/.mcassetsroot' uses unexpected schema
[11:40:49] [Render thread/WARN]: Assets URL 'union:/C:/Users/User/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.17.1-20210706.113038/client-1.17.1-20210706.113038-srg.jar%2383!/data/.mcassetsroot' uses unexpected schema
[1211月2021 11:40:49.505] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:40:50] [Render thread/INFO]: Setting user: xz123456xz
[11:40:50] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[1211月2021 11:40:52.231] [modloading-worker-9/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: patchouli, class vazkii.patchouli.common.base.Patchouli
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.17.1-37.0.107.jar%2385!:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.0.107.jar%2384!:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/ICrashCallable
	at vazkii.patchouli.common.base.Patchouli.lambda$new$0(Patchouli.java:30) ~[Patchouli-1.16.4-53.2%20(1).jar%2375!:1.16.4-53.2]
	at net.minecraftforge.fml.DistExecutor.unsafeRunForDist(DistExecutor.java:174) ~[fmlcore-1.17.1-37.0.107.jar%2384!:?]
	at net.minecraftforge.fml.DistExecutor.runForDist(DistExecutor.java:157) ~[fmlcore-1.17.1-37.0.107.jar%2384!:?]
	at vazkii.patchouli.common.base.Patchouli.<init>(Patchouli.java:30) ~[Patchouli-1.16.4-53.2%20(1).jar%2375!:1.16.4-53.2]
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.ICrashCallable
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-0.9.54.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.54.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at vazkii.patchouli.common.base.Patchouli.lambda$new$0(Patchouli.java:30) ~[Patchouli-1.16.4-53.2%20(1).jar%2375!:1.16.4-53.2]
	at net.minecraftforge.fml.DistExecutor.unsafeRunForDist(DistExecutor.java:174) ~[fmlcore-1.17.1-37.0.107.jar%2384!:?]
	at net.minecraftforge.fml.DistExecutor.runForDist(DistExecutor.java:157) ~[fmlcore-1.17.1-37.0.107.jar%2384!:?]
	at vazkii.patchouli.common.base.Patchouli.<init>(Patchouli.java:30) ~[Patchouli-1.16.4-53.2%20(1).jar%2375!:1.16.4-53.2]
	... 14 more
[11:40:52] [modloading-worker-18/INFO]: Forge mod loading, version 37.0.107, for MC 1.17.1 with MCP 20210706.113038
[11:40:52] [modloading-worker-18/INFO]: MinecraftForge v37.0.107 Initialized
[11:40:52] [Modding Legacy/blue_skies/Supporters thread/INFO]: Attempting to load the Modding Legacy supporters list from https://moddinglegacy.com/supporters-changelogs/supporters.txt
[1211月2021 11:40:52.780] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[11:40:52] [Render thread/WARN]: Removed resource pack mod_resources from options because it doesn't seem to exist anymore
[1211月2021 11:40:52.824] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundLoadEvent to a broken mod state
[1211月2021 11:40:52.884] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Block to a broken mod state
[1211月2021 11:40:52.886] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Item to a broken mod state
[11:40:53] [Modding Legacy/blue_skies/Supporters thread/INFO]: Successfully loaded the Modding Legacy supporters list.
[1211月2021 11:40:53.298] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ParticleFactoryRegisterEvent to a broken mod state
[1211月2021 11:40:53.328] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[1211月2021 11:40:53.366] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state
[1211月2021 11:40:53.366] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state
[1211月2021 11:40:53.366] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state
[11:40:53] [Render thread/INFO]: Reloading ResourceManager: Default
[1211月2021 11:40:53.473] [Worker-Main-11/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelRegistryEvent to a broken mod state
[1211月2021 11:40:53.523] [Worker-Main-14/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[1211月2021 11:40:53.523] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[1211月2021 11:40:53.523] [Worker-Main-12/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:40:57] [Worker-Main-11/WARN]: Unable to load model: 'aquaculture:iron_hook#inventory' referenced from: aquaculture:iron_hook#inventory: java.io.FileNotFoundException: aquaculture:models/item/iron_hook.json
[11:40:57] [Worker-Main-11/WARN]: Unable to load model: 'aquaculture:gold_hook#inventory' referenced from: aquaculture:gold_hook#inventory: java.io.FileNotFoundException: aquaculture:models/item/gold_hook.json
[11:40:57] [Worker-Main-11/WARN]: Unable to load model: 'aquaculture:diamond_hook#inventory' referenced from: aquaculture:diamond_hook#inventory: java.io.FileNotFoundException: aquaculture:models/item/diamond_hook.json
[11:40:57] [Worker-Main-11/WARN]: Unable to load model: 'aquaculture:light_hook#inventory' referenced from: aquaculture:light_hook#inventory: java.io.FileNotFoundException: aquaculture:models/item/light_hook.json
[11:40:57] [Worker-Main-11/WARN]: Unable to load model: 'aquaculture:heavy_hook#inventory' referenced from: aquaculture:heavy_hook#inventory: java.io.FileNotFoundException: aquaculture:models/item/heavy_hook.json
[11:40:57] [Worker-Main-11/WARN]: Unable to load model: 'aquaculture:double_hook#inventory' referenced from: aquaculture:double_hook#inventory: java.io.FileNotFoundException: aquaculture:models/item/double_hook.json
[11:40:57] [Worker-Main-11/WARN]: Unable to load model: 'aquaculture:redstone_hook#inventory' referenced from: aquaculture:redstone_hook#inventory: java.io.FileNotFoundException: aquaculture:models/item/redstone_hook.json
[11:40:57] [Worker-Main-11/WARN]: Unable to load model: 'aquaculture:note_hook#inventory' referenced from: aquaculture:note_hook#inventory: java.io.FileNotFoundException: aquaculture:models/item/note_hook.json
[11:40:57] [Worker-Main-11/WARN]: Unable to load model: 'aquaculture:nether_star_hook#inventory' referenced from: aquaculture:nether_star_hook#inventory: java.io.FileNotFoundException: aquaculture:models/item/nether_star_hook.json
[1211月2021 11:40:57.823] [Worker-Main-11/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[1211月2021 11:40:58.541] [Worker-Main-11/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:40:58] [Worker-Main-14/ERROR]: Using missing texture, unable to load minecraft:textures/entity/signs/blue_skies/lunar.png : java.io.FileNotFoundException: minecraft:textures/entity/signs/blue_skies/lunar.png
[11:40:58] [Worker-Main-12/ERROR]: Using missing texture, unable to load minecraft:textures/entity/signs/blue_skies/cherry.png : java.io.FileNotFoundException: minecraft:textures/entity/signs/blue_skies/cherry.png
[11:40:58] [Worker-Main-14/ERROR]: Using missing texture, unable to load minecraft:textures/entity/signs/blue_skies/frostbright.png : java.io.FileNotFoundException: minecraft:textures/entity/signs/blue_skies/frostbright.png
[11:40:58] [Worker-Main-12/ERROR]: Using missing texture, unable to load minecraft:textures/entity/signs/blue_skies/starlit.png : java.io.FileNotFoundException: minecraft:textures/entity/signs/blue_skies/starlit.png
[11:40:58] [Worker-Main-10/ERROR]: Using missing texture, unable to load minecraft:textures/entity/signs/blue_skies/dusk.png : java.io.FileNotFoundException: minecraft:textures/entity/signs/blue_skies/dusk.png
[11:40:58] [Worker-Main-9/ERROR]: Using missing texture, unable to load minecraft:textures/entity/signs/blue_skies/maple.png : java.io.FileNotFoundException: minecraft:textures/entity/signs/blue_skies/maple.png
[11:40:58] [Worker-Main-12/ERROR]: Using missing texture, unable to load minecraft:textures/entity/signs/blue_skies/bluebright.png : java.io.FileNotFoundException: minecraft:textures/entity/signs/blue_skies/bluebright.png
[1211月2021 11:40:58.551] [Worker-Main-11/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[1211月2021 11:40:58.576] [Worker-Main-11/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[1211月2021 11:40:58.602] [Worker-Main-11/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[1211月2021 11:40:58.609] [Worker-Main-11/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[1211月2021 11:40:58.620] [Worker-Main-11/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:40:58] [Render thread/INFO]: Loaded 0 journal_lang
[11:40:58] [Render thread/INFO]: OpenAL initialized.
[11:40:58] [Render thread/INFO]: Sound engine started
[11:40:59] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[1211月2021 11:40:59.072] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:40:59] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[1211月2021 11:40:59.073] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:40:59] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[1211月2021 11:40:59.073] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:40:59] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[1211月2021 11:40:59.074] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:40:59] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[1211月2021 11:40:59.075] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:40:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[1211月2021 11:40:59.076] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:40:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[1211月2021 11:40:59.076] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[1211月2021 11:40:59.359] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelBakeEvent to a broken mod state
[1211月2021 11:40:59.768] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$AddLayers to a broken mod state
[1211月2021 11:41:00.070] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterShadersEvent to a broken mod state
[11:41:00] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[1211月2021 11:41:00.186] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:41:00] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[1211月2021 11:41:00.187] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:41:00] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[1211月2021 11:41:00.188] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:41:00] [Render thread/FATAL]: Preparing crash report with UUID 482be8fa-069d-4b19-b580-1c9f0368274b
[11:41:00] [Render thread/FATAL]: Crash report saved to C:\Users\User\AppData\Roaming\.minecraft\crash-reports\crash-2021-11-12_11.41.00-fml.txt
[11:41:00] [Render thread/FATAL]: Preparing crash report with UUID 75c9b2e0-7c23-4664-9792-4c9ae57da550

**Comment by williewillus** [comment]
Oh, I misread your question. Patchouli Forge is not out for 1.17 yet. You're trying to run Patchouli 1.16 on 1.17, which won't work. It'll be out shortly.
