### ISSUE TITLE
Game crashes when crafting or picking up items

### ISSUE THREAD

**Issue by wakaranai266** [VazkiiMods/Patchouli#565]
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

1.18.2-71

### Modloader version

Forge: 40.1.52

### The latest.log file

https://pastebin.com/eU84Q7uF

### Issue description

as the title says my game crashes every time i pick up anything or craft anything.

### Other information

Only Mods which use Patchouli are Botania and Enigmatic Legacy

**Comment by wakaranai266** [comment]
Update: it crashes when crafting or obtaining an item which unlocks an Entry in the Enigmatic Legacy book

**Comment by williewillus** [comment]
that log does not show any crash

**Comment by wakaranai266** [comment]
So is it the wrong log or what?

**Comment by drakray** [comment]
is this related? https://pastebin.com/REpAmHBE
```
java.lang.NoSuchMethodError: 'vazkii.patchouli.client.base.PersistentData$DataHolder$BookData vazkii.patchouli.client.base.PersistentData$DataHolder.getBookData(vazkii.patchouli.common.book.Book)'
	at com.integral.enigmaticlegacy.helpers.PatchouliHelper.setEntryState(PatchouliHelper.java:26) ~[enigmaticlegacy-2.24.0.jar%23147!/:2.24.0] {re:classloading}
	at com.integral.enigmaticlegacy.helpers.PatchouliHelper.markEntryUnread(PatchouliHelper.java:41) ~[enigmaticlegacy-2.24.0.jar%23147!/:2.24.0] {re:classloading}
	at com.integral.enigmaticlegacy.packets.clients.PacketSetEntryState.lambda$handle$0(PacketSetEntryState.java:36) ~[enigmaticlegacy-2.24.0.jar%23147!/:2.24.0] {re:classloading}
	at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:213) ~[forge-1.18.2-40.1.52-universal.jar%23293!/:?] {re:classloading}
```

My game CTD when I start a world, and seamingly everytime something should update the book
Might it be on EL side?

**Comment by wakaranai266** [comment]
Seems to be related, was able to somewhat fix it by taking every item from Enigmatic Legacy in my inventory so that the book doesn't update anymore, but I don't know about the crash when you start a world because I always play on the server of a friend

**Comment by williewillus** [comment]
That's a different issue. Enigmatic Legacy is hacking around Patchouli internals, and surprise, when those internals change they get hosed. The temporary solution is to downgrade Patchouli, the actual solution is to have them not do that. Nothing is actionable on our end here.
