### ISSUE TITLE
Client Crash when Joining Server

### ISSUE THREAD

**Issue by lcy0x1** [VazkiiMods/Patchouli#661]
### Mod loader

Forge

### Minecraft version

1.19.4

### Patchouli version

1.19.4-79-FORGE

### Modloader version

45.0.50

### The latest.log file

https://discord.com/channels/154261184701267969/507986764237897728/1117665650475802734

### Issue description

I didn’t provide a latest.log because the error is not shown in log. It’s a network error that is displayed to screen directly.

it happens only in multiplayer game.

Here is the error message:
https://discord.com/channels/154261184701267969/507986764237897728/1117665650475802734

### Steps to reproduce

Install mods that has patchouli book support. Join a server with the same modlist. It happened.

**Comment by Hyy2001X** [comment]
Same problem in 1.19.4 while connect to server

> [206月2023 22:22:57.796] [Render thread/DEBUG] [patchouli/]: Loading data/tofucraft/patchouli_books/tofu_book/zh_cn/categories/strange_soy_magic.json
[206月2023 22:22:57.796] [Render thread/DEBUG] [patchouli/]: Loading data/tofucraft/patchouli_books/tofu_book/en_us/categories/strange_soy_magic.json
[206月2023 22:22:57.797] [Render thread/DEBUG] [patchouli/]: Loading data/tofucraft/patchouli_books/tofu_book/zh_cn/categories/first_step.json
[206月2023 22:22:57.797] [Render thread/DEBUG] [patchouli/]: Loading data/tofucraft/patchouli_books/tofu_book/en_us/categories/first_step.json
[206月2023 22:22:57.798] [Render thread/DEBUG] [patchouli/]: Loading data/tofucraft/patchouli_books/tofu_book/zh_cn/entries/first_step/harden_tofu.json
[206月2023 22:22:57.798] [Render thread/DEBUG] [patchouli/]: Loading data/tofucraft/patchouli_books/tofu_book/en_us/entries/first_step/harden_tofu.json
[206月2023 22:22:57.805] [Render thread/DEBUG] [patchouli/]: Loading data/tofucraft/patchouli_books/tofu_book/zh_cn/entries/first_step/get_soybeans.json
[206月2023 22:22:57.805] [Render thread/DEBUG] [patchouli/]: Loading data/tofucraft/patchouli_books/tofu_book/en_us/entries/first_step/get_soybeans.json
[206月2023 22:22:57.806] [Render thread/DEBUG] [patchouli/]: Loading data/tofucraft/patchouli_books/tofu_book/zh_cn/entries/first_step/compat.json
[206月2023 22:22:57.806] [Render thread/DEBUG] [patchouli/]: Loading data/tofucraft/patchouli_books/tofu_book/en_us/entries/first_step/compat.json
[206月2023 22:22:57.806] [Render thread/DEBUG] [patchouli/]: Loading data/tofucraft/patchouli_books/tofu_book/zh_cn/entries/first_step/before_the_making.json
[206月2023 22:22:57.806] [Render thread/DEBUG] [patchouli/]: Loading data/tofucraft/patchouli_books/tofu_book/en_us/entries/first_step/before_the_making.json
[206月2023 22:22:57.811] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/counter_category.json
[206月2023 22:22:57.811] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/microwave_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/drawer_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/nightstand_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/plate_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/sink_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/chair_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/dye_kit_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/toilet_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/freezing_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/bed_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/working_table_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/stove_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/lighting_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/cabinet_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/categories/table_category.json
[206月2023 22:22:57.812] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/microwave_crafting_entry.json
[206月2023 22:22:57.814] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/sink_crafting_entry.json
[206月2023 22:22:57.814] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/nightstand_crafting_entry.json
[206月2023 22:22:57.814] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/counter_crafting_entry.json
[206月2023 22:22:57.814] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/freezer_recipe_entry.json
[206月2023 22:22:57.814] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/toilet_usage_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/dye_kit_crafting_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/chair_usage_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/plate_usage_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/microwave_recipe_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/drawer_usage_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/working_table_usage_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/sink_usage_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/bed_usage_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/lighting_crafting_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/toilet_crafting_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/drawer_crafting_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/freezer_crafting_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/cabinet_usage_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/dye_kit_usage_entry.json
[206月2023 22:22:57.815] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/microwave_usage_entry.json
[206月2023 22:22:57.816] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/plate_crafting_entry.json
[206月2023 22:22:57.816] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/nightstand_usage_entry.json
[206月2023 22:22:57.816] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/counter_usage_entry.json
[206月2023 22:22:57.816] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/working_table_crafting_entry.json
[206月2023 22:22:57.816] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/chair_crafting_entry.json
[206月2023 22:22:57.816] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/cabinet_crafting_entry.json
[206月2023 22:22:57.816] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/bed_crafting_entry.json
[206月2023 22:22:57.816] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/freezer_usage_entry.json
[206月2023 22:22:57.816] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/stove_crafting_entry.json
[206月2023 22:22:57.816] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/stove_recipe_entry.json
[206月2023 22:22:57.816] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/stove_usage_entry.json
[206月2023 22:22:57.816] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/table_crafting_entry.json
[206月2023 22:22:57.816] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/entries/lighting_usage_entry.json
[206月2023 22:22:57.817] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/templates/freezingrecipetemplate.json
[206月2023 22:22:57.820] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/templates/stoverecipetemplate.json
[206月2023 22:22:57.820] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/templates/furniturerecipetemplate.json
[206月2023 22:22:57.821] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/templates/stoverecipe2template.json
[206月2023 22:22:57.821] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/templates/freezingrecipe2template.json
[206月2023 22:22:57.821] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/templates/furnitureusagetemplate.json
[206月2023 22:22:57.821] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/templates/craftinggridimage.json
[206月2023 22:22:57.821] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/templates/stackablespotlight.json
[206月2023 22:22:57.821] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/templates/furniturerecipe2template.json
[206月2023 22:22:57.821] [Render thread/DEBUG] [patchouli/]: Loading data/pfm/patchouli_books/guide_book/zh_cn/templates/namenumber.json
[206月2023 22:22:57.842] [Render thread/DEBUG] [oshi.util.FileUtil/]: No oshi.architecture.properties file found from ClassLoader cpw.mods.modlauncher.TransformingClassLoader@72c175f1
[206月2023 22:22:57.878] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Unreported exception thrown!
java.lang.AbstractMethodError: Receiver class com.unlikepaladin.pfm.compat.forge.patchouli.FurnitureRecipeProcessor does not define or inherit an implementation of the resolved method 'abstract void setup(net.minecraft.world.level.Level, vazkii.patchouli.api.IVariableProvider)' of interface vazkii.patchouli.api.IComponentProcessor.
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:95) ~[%5B帕秋莉手册%5D%20Patchouli-1.19.4-79-FORGE.jar%23362!/:1.19.4-79-FORGE]
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:110) ~[%5B帕秋莉手册%5D%20Patchouli-1.19.4-79-FORGE.jar%23362!/:1.19.4-79-FORGE]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:30) ~[%5B帕秋莉手册%5D%20Patchouli-1.19.4-79-FORGE.jar%23362!/:1.19.4-79-FORGE]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:247) ~[%5B帕秋莉手册%5D%20Patchouli-1.19.4-79-FORGE.jar%23362!/:1.19.4-79-FORGE]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:97) ~[%5B帕秋莉手册%5D%20Patchouli-1.19.4-79-FORGE.jar%23362!/:1.19.4-79-FORGE]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.build(BookContentsBuilder.java:95) ~[%5B帕秋莉手册%5D%20Patchouli-1.19.4-79-FORGE.jar%23362!/:1.19.4-79-FORGE]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:228) ~[%5B帕秋莉手册%5D%20Patchouli-1.19.4-79-FORGE.jar%23362!/:1.19.4-79-FORGE]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:127) ~[%5B帕秋莉手册%5D%20Patchouli-1.19.4-79-FORGE.jar%23362!/:1.19.4-79-FORGE]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[%5B帕秋莉手册%5D%20Patchouli-1.19.4-79-FORGE.jar%23362!/:1.19.4-79-FORGE]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:33) ~[%5B帕秋莉手册%5D%20Patchouli-1.19.4-79-FORGE.jar%23362!/:1.19.4-79-FORGE]
	at net.minecraft.client.multiplayer.ClientAdvancements.handler$boj000$patchouli_onSync(ClientAdvancements.java:1017) ~[client-1.19.4-20230314.122934-srg.jar%23550!/:?]
	at net.minecraft.client.multiplayer.ClientAdvancements.m_104399_(ClientAdvancements.java:57) ~[client-1.19.4-20230314.122934-srg.jar%23550!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5498_(ClientPacketListener.java:1297) ~[client-1.19.4-20230314.122934-srg.jar%23550!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:51) ~[client-1.19.4-20230314.122934-srg.jar%23550!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:16) ~[client-1.19.4-20230314.122934-srg.jar%23550!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.19.4-20230314.122934-srg.jar%23550!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.19.4-20230314.122934-srg.jar%23550!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.4-20230314.122934-srg.jar%23550!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.19.4-20230314.122934-srg.jar%23550!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.19.4-20230314.122934-srg.jar%23550!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1108) ~[client-1.19.4-20230314.122934-srg.jar%23550!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:719) ~[client-1.19.4-20230314.122934-srg.jar%23550!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[v19.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.0.66.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]

**Comment by lcy0x1** [comment]
This log should belong to another bug that happens at the same time

**Comment by williewillus** [comment]
> com.unlikepaladin.pfm.compat.forge.patchouli.FurnitureRecipeProcessor

template processor signatures changed in 1.19.4, so implementors need to update specifically for it. Please reach out to this mod author.
