### ISSUE TITLE
Patchouli does not have the right ModLoader

### ISSUE THREAD

**Issue by ShiroChan14** [VazkiiMods/Patchouli#687]
### Mod loader

Forge

### Minecraft version

1.20.1

### Patchouli version

Patchouli 1.20.1-81-FORGE.jar

### Modloader version

47.1.44

### The latest.log file

https://pastebin.com/rpJ3H7fK

### Issue description

-- MOD patchouli --
 Details:
   Mod File: /data/mods/Patchouli-1.20.1-81-FORGE.jar
   Failure message: Mod patchouli requires forge 47.1.1 or above
          Currently, forge is 47.1.0
   Mod Version: 1.20.1-81-FORGE
   Mod Issue URL: https://github.com/VazkiiMods/Patchouli
   Exception message: MISSING EXCEPTION MESSAGE
 Stacktrace:
  at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:63) ~[forge-1.20.1-47.1.0-universal.jar%23374!/:?] {re:classloading}
  at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {re:mixin}
  at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:61) ~[forge-1.20.1-47.1.0-universal.jar%23374!/:?] {re:classloading}
  at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.20.1-47.1.0-universal.jar%23374!/:?] {re:classloading}
  at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23369!/:?] {re:classloading}
   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
  at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.0.jar%2369!/:?] {}
   at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.1.0.jar%2369!/:?] {}
   at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.1.0.jar%2369!/:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
  at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
   at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
  at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
  at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
 at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

**Comment by williewillus** [comment]
The message explains it already:

Failure message: Mod patchouli requires forge 47.1.1 or above
Currently, forge is 47.1.0

Update forge.
