### ISSUE TITLE
Automatic book creation

### ISSUE THREAD

**Issue by knn-sp** [VazkiiMods/Patchouli#692]
### Mod loader

Forge

### Minecraft version

1.20.1

### Patchouli version

1.20.1-81

### Modloader version

Forge 47.1.79

### Modpack info

My modpack, there is no link

### The latest.log file

https://pastebin.com/2MP5fpHD

### Issue description

I use several mods in my modpack, and some of them are allthemodium, pedestals, etc. When I start the server it reports the error below saying to create the books, but there is no way!

Here the error:

java.lang.IllegalArgumentException: Book mysticalagradditions:guide has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[Patchouli-1.20.1-81-FORGE.jar%23389!/:1.20.1-81-FORGE]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.20.1-81-FORGE.jar%23389!/:1.20.1-81-FORGE]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.20.1-81-FORGE.jar%23389!/:1.20.1-81-FORGE]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.20.1-81-FORGE.jar%23389!/:1.20.1-81-FORGE]
	at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:76) ~[Patchouli-1.20.1-81-FORGE.jar%23389!/:1.20.1-81-FORGE]
	at vazkii.patchouli.forge.common.__ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23144!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23144!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23144!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:155) ~[javafmllanguage-1.20.1-47.1.79.jar%23427!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:124) ~[fmlcore-1.20.1-47.1.79.jar%23426!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

### Other information

If possible, resolve it as quickly as possible to create the server mod books, I really need this! And a way to disable it would be interesting.

**Comment by williewillus** [comment]
The mod adding the book `mysticalagradditions:guide` has to fix their book. This is not a Patchouli bug.
